# Generated by Django 3.1.2 on 2020-10-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=250)),
                ('lName', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
            ],
        ),
    ]
