# Generated by Django 3.1.2 on 2020-10-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fName',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='income',
            new_name='Income',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lName',
            new_name='Last_name',
        ),
    ]
